### PR TITLE
ppp_multi-file-functionality

### PR DESCRIPTION
**Pull request by joeflack4**
* Added multiple file and language conversion functionality.
* Removed default PPP configuration from erroring if there is no 'ppp_excludes' column and a preset is being used, rather than the explicit 'excludes' option.

### CODE REVIEW

**Comment by jkpr** [comment]
@joeflack4 looks like this includes the changes from a different PR (presets with excludes). Also, you have included full ODK files, which carry with them unchanged geographic identifiers. This should not be public.

1. Close the other PR if appropriate
2. Remove files with geographic identifiers from your repository.

**Comment by joeflack4** [comment]
@jkpr I actually kept them as two separate PRs. But the other PR which just makes it so that "ppp_excludes" is not a required column when using a preset is very small, so I went ahead just now and merged it with this PR as I had written earlier.

**Comment by jkpr** [comment]
@joeflack4 You need to *remove* those files from the repository, not just from a given commit onward. That means you need to re-write the commits. I am not going to merge in commits that have these files.

**Comment by joeflack4** [comment]
@jkpr Very understandable. I'm on it.

**Comment by joeflack4** [comment]
@jkpr 
#### File Removal
I was able to remove the files from the repo history via...

`git filter-branch --tree-filter 'rm -rf test/files/multiple_file_language_option_conversion' -f 8cd56d063e6f7212552f14568158a31476d07624..HEAD`

The hash starting with `8cd56d0` being the first commit in the repo. Not sure if this is the most elegant method for stipulating "whole repo history", but it appears to have worked.

I re-added the files back to just this commit, only after having stripped GIs from them.

#### Merge Conflicts
Unfortunately I'm seeing merge conflicts here in as I am viewing this PR thread, but I am not able to see the details of these conflicts in Github. Somehow this appears to have been caused by the rebasing. Any idea how best to proceed?

**Pull request merged**
